#include <gtest/gtest.h>
#include "XMLReader.h"
#include "XMLWriter.h"
#include "StringDataSource.h"
#include "StringDataSink.h"

TEST(XMLTest, NestedElements) {
    // generated by https://www.coderstool.com/xml-test-data-generator
    std::string xmltext =
        "<company>\n"
        "   <name>Msgid Software Corporation</name>\n"
        "   <address>\n"
        "       <street>2759 Eden</street>\n"
        "       <city>San Francisco</city>\n"
        "       <state>Nevada</state>\n"
        "       <zip>AL40182</zip>\n"
        "   </address>\n"
        "   <ceo>Lester Kang</ceo>\n"
        "   <dateCreated>1980-02-10</dateCreated>\n"
        "</company>";

    auto source = std::make_shared<CStringDataSource>(xmltext);
    CXMLReader reader(source);

    EXPECT_FALSE(reader.End());

    SXMLEntity entity;

    // <company>
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::StartElement);
    EXPECT_EQ(entity.DNameData, "company");

    // <name>
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::StartElement);
    EXPECT_EQ(entity.DNameData, "name");

    // "Msgid Software Corporation"
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::CharData);
    EXPECT_EQ(entity.DNameData, "Msgid Software Corporation");

    // </name>
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::EndElement);
    EXPECT_EQ(entity.DNameData, "name");

    // <address>
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::StartElement);
    EXPECT_EQ(entity.DNameData, "address");

    // <street>
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::StartElement);
    EXPECT_EQ(entity.DNameData, "street");

    // "2759 Eden"
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::CharData);
    EXPECT_EQ(entity.DNameData, "2759 Eden");

    // </street>
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::EndElement);
    EXPECT_EQ(entity.DNameData, "street");

    // <city>
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::StartElement);
    EXPECT_EQ(entity.DNameData, "city");

    // "San Francisco"
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::CharData);
    EXPECT_EQ(entity.DNameData, "San Francisco");

    // </city>
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::EndElement);
    EXPECT_EQ(entity.DNameData, "city");

    // <state>
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::StartElement);
    EXPECT_EQ(entity.DNameData, "state");

    // "Nevada"
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::CharData);
    EXPECT_EQ(entity.DNameData, "Nevada");

    // </state>
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::EndElement);
    EXPECT_EQ(entity.DNameData, "state");

    // <zip>
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::StartElement);
    EXPECT_EQ(entity.DNameData, "zip");

    // "AL40182"
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::CharData);
    EXPECT_EQ(entity.DNameData, "AL40182");

    // </zip>
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::EndElement);
    EXPECT_EQ(entity.DNameData, "zip");

    // </address>
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::EndElement);
    EXPECT_EQ(entity.DNameData, "address");

    // <ceo>
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::StartElement);
    EXPECT_EQ(entity.DNameData, "ceo");

    // "Lester Kang"
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::CharData);
    EXPECT_EQ(entity.DNameData, "Lester Kang");

    // </ceo>
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::EndElement);
    EXPECT_EQ(entity.DNameData, "ceo");

    // <dateCreated>
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::StartElement);
    EXPECT_EQ(entity.DNameData, "dateCreated");

    // "1980-02-10"
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::CharData);
    EXPECT_EQ(entity.DNameData, "1980-02-10");

    // </dateCreated>
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::EndElement);
    EXPECT_EQ(entity.DNameData, "dateCreated");

    // </company>
    EXPECT_TRUE(reader.ReadEntity(entity, false));
    EXPECT_EQ(entity.DType, SXMLEntity::EType::EndElement);
    EXPECT_EQ(entity.DNameData, "company");

    // no more
    EXPECT_FALSE(reader.ReadEntity(entity, false));
    EXPECT_TRUE(reader.End());
}


TEST(XMLTest, WriteAndFlush) {
    SXMLEntity startRoot{SXMLEntity::EType::StartElement, "company"};
    SXMLEntity nameElem{SXMLEntity::EType::StartElement, "name"};
    SXMLEntity nameText{SXMLEntity::EType::CharData, "Msgid Software Corporation"};
    SXMLEntity endName{SXMLEntity::EType::EndElement, "name"};

    SXMLEntity addressElem{SXMLEntity::EType::StartElement, "address"};
    SXMLEntity addressText{SXMLEntity::EType::CharData, "some address text"};
    SXMLEntity endAddress{SXMLEntity::EType::EndElement, "address"};

    SXMLEntity endRoot{SXMLEntity::EType::EndElement, "company"};

    auto sink = std::make_shared<CStringDataSink>();
    {
        CXMLWriter writer(sink);
        writer.WriteEntity(startRoot);
        writer.WriteEntity(nameElem);
        writer.WriteEntity(nameText);
        writer.WriteEntity(endName);
        writer.WriteEntity(addressElem);
        writer.WriteEntity(addressText);
        writer.WriteEntity(endAddress);

        //test: flush()
        writer.Flush(); 
    }

    std::string output = sink->String();
    EXPECT_NE(std::string::npos, output.find("<company>"));
    EXPECT_NE(std::string::npos, output.find("<name>Msgid Software Corporation</name>"));
    EXPECT_NE(std::string::npos, output.find("<address>some address text</address>"));
    EXPECT_NE(std::string::npos, output.find("</company>"));
}


